kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-producer
      name: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
        name: kafka-producer
    spec:
      containers:
      - name: kafka-producer
        image: youten/sdtd-project:1.0.0
        command:
        - sh
        - -c
        - "exec tail -f /dev/null"
       