apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: slow
provisioner: kubernetes.io/aws-ebs
parameters:
  type: io1
  iopsPerGB: "10"
  fsType: ext4
---
apiVersion: v1
kind: PersistentVolume
metadata:
 name: ex-volume
 labels:
  type: aws-storage
spec:
 storageClassName: slow
 capacity:
  storage: 6Gi
 accessModes:
  - ReadWriteOnce
 hostPath:
  path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: ex-claim
spec:
 storageClassName: slow
 accessModes:
  - ReadWriteOnce
 resources:
  requests:
   storage: 2Gi
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: kafka-deployment
spec:
  serviceName: kafka-service
  replicas: 2
  selector:
    matchLabels:
      app: kafka
      id: "0"
  template:
    metadata:
      labels:
        app: kafka
        id: "0"
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: kafka-service
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zoo1:2181,zoo2:2181,zoo3:2181
        - name: KAFKA_CREATE_TOPICS
          value: NewsTopic:2:1,ActorTopic:2:1
        volumeMounts:
        - mountPath: /var/lib/kafka
          name: kafka-data
      volumes: 
      - name: kafka-data
        persistentVolumeClaim:
          claimName: ex-claim